"commit_message": "Add(lang): New translations %original_file_name% from Crowdin"
"append_commit_message": false

files:
  - source: /src/main/resources/assets/languages/en_US.json
    translation: /src/main/resources/assets/languages/%locale_with_underscore%.json
